### ISSUE TITLE
Windows phone 8.1 for Moto e 2014

### ISSUE THREAD

**Issue by Vicc2008** [aravindvnair99/Motorola-Moto-E-XT1022-condor-unbrick#2]
Please need help me with moto e 2014 xt1021 for install Windows phone 8.1

My moto e 2014 in edl

**Comment by aravindvnair99** [comment]
> Please need help me with moto e 2014 xt1021 for install Windows phone 8.1

@Vicc2008 Please provide more information on the issue you are facing.

**Comment by Vicc2008** [comment]
My moto e 2014 is bricked
